QR Code Generation Script
SuperteamDAO/solathon pull request #47
Opened 2024-01-11 12:16 UTC by suhasasumukh

Changes made:

- Made the logo path a parameter with a default value
- Combined the logo resizing logic to improve readability
- Used os.path.join to create the logo path.

2024-01-11 21:57 UTC, GitBolt commented
Did you try running it? Seems like os.path.join part is removed and the readability doesn't seem to be effected that much with the changes

2024-01-12 11:26 UTC, RevTpark commented
btw, the solana pay docs itself doesn't allow changing the logo path since it represents it is made by Solana Pay.

2024-01-12 11:28 UTC, RevTpark commented on solathon/solana_pay/create_qr.py
> +def create_qr(link: str, size: int = 10, background: str = 'white', color: str = 'black', border: int = 2, logo_path: str = "qr-logo.png") -> BytesIO:
We cant let users add their own logo right now
refer `https://docs.solanapay.com/api/core/function/createQR`

2024-01-12 17:26 UTC, suhasasumukh commented on solathon/solana_pay/create_qr.py
> +def create_qr(link: str, size: int = 10, background: str = 'white', color: str = 'black', border: int = 2, logo_path: str = "qr-logo.png") -> BytesIO:
oh I have resolved it

2024-01-12 17:26 UTC, suhasasumukh commented
> Did you try running it? Seems like os.path.join part is removed and the readability doesn't seem to be effected that much with the changes

it must be fixed now

2024-01-12 17:29 UTC, RevTpark requested changes

2024-01-12 17:29 UTC, RevTpark commented on solathon/solana_pay/create_qr.py
> +        logo_path (str): The path to the fixed logo image.
Not a param anymore

2024-01-12 17:33 UTC, suhasasumukh commented on solathon/solana_pay/create_qr.py
> +        logo_path (str): The path to the fixed logo image.
@RevTpark fixed

2024-01-13 18:06 UTC, suhasasumukh commented
@GitBolt it should be working fine now

2024-01-19 06:14 UTC, GitBolt commented
Well, there were plenty of commits there just to have the changes introduced to be reversed back. The formatting is a very minor change left only. Merging won't make sense here.

2024-01-19 06:14 UTC, closed without merging